modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/BetterThanLlamas/issues"

[[mods]]
    modId="betterthanllamas"
    version="${file.jarVersion}" #mandatory
    displayName="Better Than Llamas"
    displayURL="http://ichun.me/mods/better-than-llamas/"
    authors="iChun"
    description='''
    Better Than Llamas! #BlameWyld
    https://twitter.com/Wyld/status/846489501320982528
    '''

[[dependencies.betterthanllamas]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterthanllamas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
